### ISSUE TITLE
Works with Images

### ISSUE THREAD

**Issue by juanjoguevara** [spincle/Spatial-Media-For-iOS#1]
Its possible use this library to inject 360º Photo Metadata?

**Comment by tomtomtong** [comment]
Not possible I use the library below to do.
https://www.chilkatsoft.com/xmp-objc.asp
But you need to buy the license from them.

**Comment by tomtomtong** [comment]
If you just want to upload image to facebook as photosphere effect, you could use my new repo
https://github.com/spincle/photosphereImageFBuploader
